[package]
name = "exonum-multisig"
version = "0.1.0"
authors = ["Nikk Radetskiy <metsawyr@gmail.com>"]
edition = "2018"

[dependencies]
exonum = "0.9.0"
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
failure = "0.1.1"